export var users = [
  {
    username: "raj_kumar92",
    gender: "Male",
    city: "Delhi",
    email: "raj_kumar92@gmail.com",
    image_url: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    username: "dev_malhotra11",
    gender: "Male",
    city: "Hyderabad",
    email: "dev_malhotra11@gmail.com",
    image_url: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    username: "kiran_kumar14",
    gender: "Male",
    city: "Nagpur",
    email: "kiran_kumar14@hotmail.com",
    image_url: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    username: "sunita_rani65",
    gender: "Female",
    city: "Bhopal",
    email: "sunita_rani65@gmail.com",
    image_url: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    username: "manoj_gupta76",
    gender: "Male",
    city: "Patna",
    email: "manoj_gupta76@yahoo.com",
    image_url: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    username: "divya_nair08",
    gender: "Female",
    city: "Thiruvananthapuram",
    email: "divya.nair08@gmail.com",
    image_url: "https://randomuser.me/api/portraits/women/7.jpg",
  },
  {
    username: "sanjay_yadav60",
    gender: "Male",
    city: "Indore",
    email: "sanjay_yadav60@gmail.com",
    image_url: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    username: "meena_rao39",
    gender: "Female",
    city: "Mysore",
    email: "meena.rao39@hotmail.com",
    image_url: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    username: "rahul_mishra25",
    gender: "Male",
    city: "Kanpur",
    email: "rahul_mishra25@yahoo.com",
    image_url: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    username: "deepika_joshi91",
    gender: "Female",
    city: "Amritsar",
    email: "deepika.joshi91@gmail.com",
    image_url: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    username: "vijay_sen44",
    gender: "Male",
    city: "Ranchi",
    email: "vijay_sen44@hotmail.com",
    image_url: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    username: "neha_sharma88",
    gender: "Female",
    city: "Mumbai",
    email: "neha.sharma88@yahoo.com",
    image_url: "https://randomuser.me/api/portraits/women/1.jpg",
  },
  {
    username: "arjun_singh21",
    gender: "Male",
    city: "Kolkata",
    email: "arjun.singh21@gmail.com",
    image_url: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    username: "priya_mehta07",
    gender: "Female",
    city: "Ahmedabad",
    email: "priya_mehta07@hotmail.com",
    image_url: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    username: "vivek_rana99",
    gender: "Male",
    city: "Pune",
    email: "vivek_rana99@gmail.com",
    image_url: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    username: "ananya_das18",
    gender: "Female",
    city: "Bangalore",
    email: "ananya.das18@gmail.com",
    image_url: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    username: "amit_verma83",
    gender: "Male",
    city: "Chandigarh",
    email: "amit_verma83@yahoo.com",
    image_url: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    username: "isha_kapoor56",
    gender: "Female",
    city: "Lucknow",
    email: "isha.kapoor56@gmail.com",
    image_url: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    username: "rohit_patel32",
    gender: "Male",
    city: "Surat",
    email: "rohit_patel32@gmail.com",
    image_url: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    username: "pooja_jain47",
    gender: "Female",
    city: "Jaipur",
    email: "pooja.jain47@yahoo.com",
    image_url: "https://randomuser.me/api/portraits/women/5.jpg",
  },
];
